package system.bld.dao;

import java.util.List;
import java.util.Map;

import system.bld.model.HotNewsRecords;

public interface HotNewsRecordsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_news_records
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_news_records
     *
     * @mbg.generated
     */
    int insert(HotNewsRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_news_records
     *
     * @mbg.generated
     */
    HotNewsRecords selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_news_records
     *
     * @mbg.generated
     */
    List<HotNewsRecords> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_news_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotNewsRecords record);

    /**
     * 分页查询
     * @return
     */
    List<HotNewsRecords> selectToDayPageList(Map<String,Object> map);
}