package system.bld.dao;

import java.util.List;
import java.util.Map;

import system.bld.model.UserLoginLog;

/**
 * @author LiTao
 */
public interface UserLoginLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbg.generated
     */
    int insert(UserLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbg.generated
     */
    UserLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbg.generated
     */
    List<UserLoginLog> selectAll();

    List<UserLoginLog> selectListLimit100();

    List<UserLoginLog> selectPageList(Map<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserLoginLog record);
}